package Db.dao;

import java.sql.ResultSet;
import java.sql.SQLException;



import Db.HsqlUnitOfWork;

import cdbase.Cd;
import Db.dao.HsqlDaoBase;

public class HsqlCdDao extends HsqlDaoBase<Cd> implements CdDao {
	
	public HsqlCdDao(HsqlUnitOfWork uow) {
		super(uow);
		
	}
	@Override
	protected String getTableName() {
		return "cd";
	}

	@Override
	protected String getCreateQuery() {
		return "CREATE TABLE cd("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(50),"
				+ "price int,"
				+ ")";
	}

	@Override
	protected String getInsertQuery() {
		return "insert into cd(name,price) values (?,?)";
	}

	@Override
	protected String getUpdateQuery() {
		return "update cd set"
				+ "(name,price)=(?,?)"
				+ "where id=?";
	}
	public void setAuthores(Cd c) {
		// TODO Auto-generated method stub
		
	}
	public void setTracks(Cd c) {
		// TODO Auto-generated method stub
		
	}
	@Override
	protected void setUpdateQuery(Cd ent) throws SQLException {
		
		update.setString(1, ent.getName());
		update.setInt(2, ent.getPrice());
		update.setInt(3, ent.getId());
		
	}
	@Override
	protected Cd build(ResultSet rs) throws SQLException {
		Cd c = new Cd();
		c.setName(rs.getString("name"));
		c.setPrice(rs.getInt("price"));
		c.setId(rs.getInt("id"));
		return c;
		
	}
	@Override
	protected void setInsertQuery(Cd ent) throws SQLException {
		insert.setString(1, ent.getName());
		insert.setInt(2, ent.getPrice());
		
		
	}


	

	}

