package Db.dao;

import java.sql.ResultSet;
import java.sql.SQLException;


import Db.HsqlUnitOfWork;

import cdbase.Track;
import Db.dao.HsqlDaoBase;

public class HsqlTrackDao extends HsqlDaoBase<Track> {
	
	public HsqlTrackDao(HsqlUnitOfWork uow) {
		super(uow);
	}
	
	@Override
	protected void setUpdateQuery(Track ent) throws SQLException {

		update.setString(1, ent.getName());
		update.setDouble(3, ent.getTime());
		update.setInt(4, ent.getNumber());
		update.setInt(5, ent.getId());
		
	}

	@Override
	protected Track build(ResultSet rs) throws SQLException {

		Track t = new Track();
		t.setName(rs.getString("name"));
		t.setTime(rs.getDouble("time"));
		t.setNumber(rs.getInt("number"));
		t.setId(rs.getInt("id"));
		return t;
	}

	@Override
	protected void setInsertQuery(Track ent) throws SQLException {
		insert.setString(1, ent.getName());
		insert.setDouble(2, ent.getTime());
		insert.setInt(3, ent.getNumber());
		
		
	}

	@Override
	protected String getTableName() {
		return "track";
	}

	@Override
	protected String getCreateQuery() {
		return "CREATE TABLE Track("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(50),"
				+ "time DOUBLE,"
				+ "number INT"
				+ ")";
	}

	@Override
	protected String getInsertQuery() {
		return "insert into track(name,time,number) values (?,?,?)";
	}

	@Override
	protected String getUpdateQuery() {
		return "update client set"
				+ "(name,time,number)=(?,?,?)"
				+ "where id=?";
	}

	
}
	
	
	
